name: Pytest API Testing

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  Pytest-API-Testing:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install allure-pytest   # <--- 关键：安装 allure-pytest

    - name: Test with pytest
      run: |
        ENV=dev pytest tests/ --alluredir=./allure-results   # <--- 生成原始数据

    - name: Generate Allure Report
      uses: andgineer/allure-report@v3.6   # <--- 使用第三方 Action 生成报告
      if: always()   # 即使测试失败也生成报告
      with:
        allure-results: ./allure-results   # 指定原始数据目录

    - name: Upload Allure report as artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-report
        path: allure-report   # andgineer/allure-report 默认输出到 allure-report 目录